### ISSUE TITLE
Most Function.prototype.bind questions have errors, intention unclear

### ISSUE THREAD

**Issue by etrepum** [cspa-exam/open-standards#4]
https://github.com/cspa-exam/open-standards/blob/02446451f26e5c337c38063222d1fa9a9aaf2742/standards/JavaScript/2.3-keword-_this-binding.xml#L198-L296

It's not clear which of these are supposed to have errors, if any, but all of them do because there's no `greet` property on `alice`.

**Comment by gilbert** [comment]
Thanks for pointing this out! Most of these should be `greet.bind` instead of `alice.greet.bind`. I will update this promptly.
